#!/bin/bash
# generate-changelog.sh – Generate release changelog from git log + PR titles
# Usage: ./scripts/generate-changelog.sh [from_ref] [to_ref]
# If no refs given, uses last tag -> HEAD

set -euo pipefail

FROM="${1:-$(git describe --tags --abbrev=0 2>/dev/null || git log --oneline --reverse | head -1 | awk '{print $1}')}"
TO="${2:-HEAD}"

echo "## Changelog"
echo ""
echo "Changes since \`${FROM}\` to \`${TO}\`:"
echo ""

# Get raw commit log
COMMITS=$(git log --oneline "${FROM}..${TO}" 2>/dev/null || git log --oneline "${FROM}..${TO}" 2>/dev/null)

if [ -z "$COMMITS" ]; then
  echo "No changes found between ${FROM} and ${TO}."
  exit 0
fi

# Check if gh is available
HAS_GH=false
command -v gh &>/dev/null && HAS_GH=true

# Group commits
FEATURES=""
FIXES=""
CHORES=""
DOCS=""
OTHER=""

while IFS= read -r line; do
  HASH=$(echo "$line" | awk '{print $1}')
  MSG=$(echo "$line" | cut -d' ' -f2-)

  # Try to get PR number from commit message
  PR=""
  if echo "$MSG" | grep -qE '#[0-9]+'; then
    PR=$(echo "$MSG" | grep -oE '#[0-9]+' | head -1)
  fi

  ENTRY="- ${MSG} (${HASH}${PR:+ $PR})"

  case "$MSG" in
    feat:*|feature:*|"feat("*)
      FEATURES="$FEATURES\n$ENTRY"
      ;;
    fix:*|"fix("*)
      FIXES="$FIXES\n$ENTRY"
      ;;
    chore:*|refactor:*|"chore("*|"refactor("*)
      CHORES="$CHORES\n$ENTRY"
      ;;
    docs:*|"docs("*)
      DOCS="$DOCS\n$ENTRY"
      ;;
    *)
      OTHER="$OTHER\n$ENTRY"
      ;;
  esac
done <<< "$COMMITS"

# Try to augment with PR data from gh if available
if [ "$HAS_GH" = true ]; then
  # Get PRs merged in this range for richer descriptions
  GH_DATA=$(gh pr list --state merged --base main --limit 50 --json number,title,author 2>/dev/null || true)
fi

[ -n "$FEATURES" ] && echo -e "### ✨ Features\n${FEATURES}\n"
[ -n "$FIXES" ] && echo -e "### 🐛 Bug Fixes\n${FIXES}\n"
[ -n "$CHORES" ] && echo -e "### 🛠 Maintenance\n${CHORES}\n"
[ -n "$DOCS" ] && echo -e "### 📚 Documentation\n${DOCS}\n"
[ -n "$OTHER" ] && echo -e "### 🔹 Other\n${OTHER}\n"

echo "---"
echo "_Generated by scripts/generate-changelog.sh_"
